image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  BASE_IMAGE_NAME: emcmongoose/mongoose
  IMAGE_NAME: emcmongoose/mongoose-storage-driver-hdfs

services:
  - docker:dind

stages:
  - build
  - publish_docker_image
  - test
  - deploy

before_script:
  - apk add --no-cache --update openjdk8

build:
  stage: build
  script:
    - ./gradlew jar
  artifacts:
    paths:
    - build/libs/mongoose-storage-driver-hdfs.jar

publish_docker_image:
  stage: publish_docker_image
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - docker build --build-arg MONGOOSE_VERSION=${MONGOOSE_VERSION} -f docker/Dockerfile -t ${IMAGE_NAME}:${CI_COMMIT_SHA} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHA}

test_integration:
  stage: test
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - "./gradlew test --tests com.emc.mongoose.storage.driver.hdfs.integration.*"

test_acceptance:
  stage: test
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - export MONGOOSE_VERSION=$(cat build.gradle | grep "mongoose:" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
    - "./gradlew test --tests com.emc.mongoose.storage.driver.hdfs.system.*"
