---
storage:
  net:
    bindBacklogSize: int
    interestOpQueued: boolean
    keepAlive: boolean
    linger: int
    reuseAddr: boolean
    rcvBuf: int
    sndBuf: int
    tcpNoDelay: boolean
    timeoutMilliSec: int
    ssl: boolean
    node:
      addrs: list
      connAttemptsLimit: int
      port: int
      slice: boolean
